services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/rails
    depends_on:
      - db
      - elasticsearch
    env_file:
      - .env
    networks:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - backend

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
